-- Mevcut kamu sitesi içeriğini tek veri kaynağı olarak Supabase'e taşır.
-- Idempotenttir: daha önce taşınmış kayıtları veya panelde yapılan değişiklikleri ezmez.

insert into page_content (page_key, section_key, draft_content, published_content, requires_verification, published_at)
values
  ('site', 'profile',
   '{"name":"Ekrem Eray Arda","title":"İBB ve Kartal Belediye Meclis Üyesi","description":"Ekrem Eray Arda''nın çalışmaları, açıklamaları ve medya içerikleri için kişisel kamusal web sitesi."}'::jsonb,
   '{"name":"Ekrem Eray Arda","title":"İBB ve Kartal Belediye Meclis Üyesi","description":"Ekrem Eray Arda''nın çalışmaları, açıklamaları ve medya içerikleri için kişisel kamusal web sitesi."}'::jsonb,
   false, now()),
  ('about', 'biography',
   $json${
     "heroSummary":"1985 yılında İstanbul'da doğan Ekrem Eray Arda, ilk ve ortaöğrenimini Kartal'da tamamladı. İş dünyası, spor ve yerel yönetimlerde görev aldı. 2024 yılından bu yana Kartal ve İstanbul Büyükşehir Belediye Meclislerinde görev yapmaktadır.",
     "sections":[
       {"number":"01","category":"Hakkında","title":"Kartal'dan İstanbul'a uzanan bir yaşam.","paragraphs":["İstanbul'da doğan ve ilk eğitim yıllarını Kartal'da geçiren Ekrem Eray Arda, eğitimini siyaset bilimi ve uluslararası ilişkiler alanlarında sürdürdü. Spor, iş dünyası ve yerel yönetimlerde farklı görevler üstlendi."]},
       {"number":"02","category":"Eğitim","title":"Eğitim ve akademik yaşam","paragraphs":["25 Mart 1985'te İstanbul'da doğdu. Girne Amerikan Üniversitesi'nde İşletme eğitimi aldı. İstanbul Bilgi Üniversitesi Siyaset Bilimi Bölümü'nden mezun oldu ve Bahçeşehir Üniversitesi'nde Küresel Siyaset ve Uluslararası İlişkiler alanında yüksek lisans yaptı."]},
       {"number":"03","category":"Spor","title":"Disiplin, Azim ve Takım Ruhu","paragraphs":["1999–2004 yılları arasında Fenerbahçe Kürek Takımı'nda sporcu olarak yer aldı ve takım kaptanlığı yaptı."]},
       {"number":"04","category":"İş Hayatı","title":"Girişimcilik ve yönetim tecrübesi","paragraphs":["Genç yaşlardan itibaren iş dünyasında farklı alanlarda faaliyet gösteren Ekrem Eray Arda, girişimcilik ve yöneticilik alanlarında deneyim kazandı."]},
       {"number":"05","category":"Siyasi Yaşam","title":"Siyasi yaşam ve yerel yönetim","paragraphs":["2019 yılında Çekmeköy Belediye Meclis Üyesi seçildi. Demokrat Parti İstanbul İl Başkanlığı görevini yürüttü. 2024 yerel seçimlerinde Kartal Belediye Meclisi ve İstanbul Büyükşehir Belediye Meclisine seçildi. Eylül 2026'da CHP'den ayrılarak görevlerine bağımsız meclis üyesi olarak devam edeceğini açıkladı."],"subsections":[{"title":"Meclis ve komisyon görevleri","paragraphs":["Kartal Belediye Meclisi Gençlik ve Spor Komisyonu Başkanı ve AB ve Dış İlişkiler Komisyonu üyesidir. İstanbul Büyükşehir Belediye Meclisinde Gençlik ve Spor Komisyonu üyeliği görevini de yürütmektedir."]}],"requiresOfficialVerification":true}
     ]
   }$json$::jsonb,
   $json${
     "heroSummary":"1985 yılında İstanbul'da doğan Ekrem Eray Arda, ilk ve ortaöğrenimini Kartal'da tamamladı. İş dünyası, spor ve yerel yönetimlerde görev aldı. 2024 yılından bu yana Kartal ve İstanbul Büyükşehir Belediye Meclislerinde görev yapmaktadır.",
     "sections":[
       {"number":"01","category":"Hakkında","title":"Kartal'dan İstanbul'a uzanan bir yaşam.","paragraphs":["İstanbul'da doğan ve ilk eğitim yıllarını Kartal'da geçiren Ekrem Eray Arda, eğitimini siyaset bilimi ve uluslararası ilişkiler alanlarında sürdürdü. Spor, iş dünyası ve yerel yönetimlerde farklı görevler üstlendi."]},
       {"number":"02","category":"Eğitim","title":"Eğitim ve akademik yaşam","paragraphs":["25 Mart 1985'te İstanbul'da doğdu. Girne Amerikan Üniversitesi'nde İşletme eğitimi aldı. İstanbul Bilgi Üniversitesi Siyaset Bilimi Bölümü'nden mezun oldu ve Bahçeşehir Üniversitesi'nde Küresel Siyaset ve Uluslararası İlişkiler alanında yüksek lisans yaptı."]},
       {"number":"03","category":"Spor","title":"Disiplin, Azim ve Takım Ruhu","paragraphs":["1999–2004 yılları arasında Fenerbahçe Kürek Takımı'nda sporcu olarak yer aldı ve takım kaptanlığı yaptı."]},
       {"number":"04","category":"İş Hayatı","title":"Girişimcilik ve yönetim tecrübesi","paragraphs":["Genç yaşlardan itibaren iş dünyasında farklı alanlarda faaliyet gösteren Ekrem Eray Arda, girişimcilik ve yöneticilik alanlarında deneyim kazandı."]},
       {"number":"05","category":"Siyasi Yaşam","title":"Siyasi yaşam ve yerel yönetim","paragraphs":["2019 yılında Çekmeköy Belediye Meclis Üyesi seçildi. Demokrat Parti İstanbul İl Başkanlığı görevini yürüttü. 2024 yerel seçimlerinde Kartal Belediye Meclisi ve İstanbul Büyükşehir Belediye Meclisine seçildi. Eylül 2026'da CHP'den ayrılarak görevlerine bağımsız meclis üyesi olarak devam edeceğini açıkladı."],"subsections":[{"title":"Meclis ve komisyon görevleri","paragraphs":["Kartal Belediye Meclisi Gençlik ve Spor Komisyonu Başkanı ve AB ve Dış İlişkiler Komisyonu üyesidir. İstanbul Büyükşehir Belediye Meclisinde Gençlik ve Spor Komisyonu üyeliği görevini de yürütmektedir."]}],"requiresOfficialVerification":true}
     ]
   }$json$::jsonb,
   true, now())
on conflict (page_key, section_key) do nothing;

insert into site_settings (key, value)
values ('social_links', '[{"id":"instagram","label":"Instagram","href":"https://www.instagram.com/ekrem.eray.arda/"},{"id":"facebook","label":"Facebook","href":"https://www.facebook.com/E.ErayArda"},{"id":"x","label":"X","href":"https://x.com/EkremErayArda"}]'::jsonb)
on conflict (key) do nothing;

with seed(slug,title,summary,body,event_date,event_end_date,event_date_approx,date_note,categories,location,kind,status,missing_info,sort_order) as (
  values
  ('kartal-uluslararasi-tasarim-bulusmasi','Kartal''da Uluslararası Tasarım Buluşması','The Great Game — Uluslararası Tasarım Yaz Okulu kapsamında Kartal''da gerçekleştirilen etkinlikler.','["Ekrem Eray Arda, Kartal''da düzenlenen The Great Game uluslararası tasarım programı kapsamında gerçekleştirilen etkinliklere katıldı. Genç mimarların ve tasarımcıların bir araya geldiği programın açılış ve kapanış süreçlerine ilişkin paylaşımlarda bulundu."]'::jsonb,'2026-08-29'::date,'2026-09-08'::date,null,'Program 29 Ağustos – 8 Eylül 2026 tarihleri arasında yapıldı (doğrulandı). Arda''nın hangi günlerde katıldığı doğrulanmadı.',array['etkinlikler'],'kartal','katilim'::activity_kind,'published'::publication_status,array['Arda''nın programa katılımını doğrulayan bağımsız kaynak bulunamadı — haberlerde adı geçmiyor.','Arda''nın katıldığı toplantıların kesin tarihleri.','Açılış ve kapanış programındaki rolü (varsa resmî kayıt).','Makina Hangar etkinlik fotoğrafları — kullanım izniyle birlikte.','DİKKAT: Haber kaynaklarında geçen ''Alp Arda'' programın koordinatörüdür, Ekrem Eray Arda ile karıştırılmamalıdır.'],1),
  ('michele-bonino-spor-bulusmasi','Michele Bonino ile Spor Buluşması','Politecnico di Torino''dan Michele Bonino ile Fenerbahçe Kürek Şubesi ve Dragos Su Sporları Merkezi buluşması.','["Ekrem Eray Arda, Politecnico di Torino''dan akademisyen Michele Bonino ile Fenerbahçe Kürek Şubesi''ni ziyaret etti. Kürek sporunun da yer aldığı buluşmanın ardından Dragos Su Sporları Merkezi''nde bir araya geldiler."]'::jsonb,null,null,'2026-09','Eylül 2026 (gün doğrulanmadı).',array['ziyaretler','genclik-spor'],'istanbul','katilim'::activity_kind,'published'::publication_status,array['Ziyareti doğrulayan hiçbir kaynak bulunamadı.','Kesin tarih.','Ziyaretin kapsamı ve katılımcı listesi.','Fotoğraflar — kullanım izniyle birlikte.'],2),
  ('emre-arolat-mimarlik-semineri','Emre Arolat''ın Mimarlık Semineri','The Great Game programı kapsamında mimar Emre Arolat''ın katılımıyla düzenlenen seminer.','["Ekrem Eray Arda, The Great Game programı kapsamında mimar Emre Arolat''ın katılımıyla gerçekleştirilen mimarlık seminerine iştirak etti."]'::jsonb,null,null,'2026-09','Eylül 2026 (gün doğrulanmadı).',array['etkinlikler'],'kartal','katilim'::activity_kind,'published'::publication_status,array['Seminerin The Great Game programı kapsamında yapıldığını doğrulayan kaynak bulunamadı.','Kesin tarih ve yer.','Arda''nın katılımını gösteren doğrudan paylaşım bağlantısı.','Fotoğraflar — kullanım izniyle birlikte.'],3),
  ('kartal-belediye-meclisi-eylul-toplantisi','Kartal Belediye Meclisi Eylül Toplantısı','Kartal Belediye Meclisinin eylül ayı olağan toplantısına katılım.','["Ekrem Eray Arda, Kartal Belediye Meclisinin eylül ayındaki toplantısına katılımına ilişkin paylaşım yaptı."]'::jsonb,null,null,'2026-09','Eylül 2026 (kesin gün resmî meclis takviminden doğrulanmalı).',array['meclis'],'kartal','calisma'::activity_kind,'published'::publication_status,array['Toplantının kesin tarihi — resmî meclis takviminden doğrulanmalı.','Arda''nın katılımını gösteren yoklama veya tutanak kaydı.','Konuşma, önerge veya karardaki doğrudan rolü belgelenmedikçe metne eklenmeyecek.','Fotoğraf yok.'],4),
  ('kartal-talepleri-ibbye-iletildi','Kartal''ın Taleplerinin İBB''ye İletilmesi','Kartal Belediye Başkanı ve meclis grubuyla birlikte İBB Başkan Vekili ile yapılan görüşme.','["Ekrem Eray Arda, Kartal Belediye Başkanı Gökhan Yüksel ve belediye meclisi grubuyla birlikte İBB Başkan Vekili Nuri Aslan''la yapılan görüşmeye katıldığını ve Kartallıların taleplerinin iletildiğini açıkladı."]'::jsonb,null,null,'2026-08','Ağustos 2026 (gün doğrulanmadı).',array['meclis','ziyaretler'],'istanbul','calisma'::activity_kind,'published'::publication_status,array['Görüşmeyi doğrulayan kurumsal duyuru veya haber bulunamadı.','Kesin görüşme tarihi ve katılımcı listesi.','İletilen taleplerin içeriği — belgelenmedikçe metne eklenmeyecek.','Fotoğraflar — kullanım izniyle birlikte.'],5),
  ('dragos-denizcilik-ve-kabotaj-bayrami','Dragos''ta Denizcilik ve Kabotaj Bayramı','Kartal Dragos Su Sporları İskelesi''nde düzenlenen Denizcilik ve Kabotaj Bayramı etkinliği.','["Ekrem Eray Arda, Kartal Dragos Su Sporları İskelesi''nde düzenlenen Denizcilik ve Kabotaj Bayramı etkinliğine katıldı."]'::jsonb,null,null,null,'1 Temmuz — YIL DOĞRULANMADI. Kartal Belediyesi bu etkinliği her yıl düzenliyor; hangi yılın kastedildiği belirsiz.',array['etkinlikler','genclik-spor'],'kartal','katilim'::activity_kind,'draft'::publication_status,array['ETKİNLİĞİN YILI belirlenmeden yayımlanmayacak — kullanıcı talimatı.','Arda''nın katılımını doğrulayan kaynak bulunamadı.','İlgili Kartal Belediyesi haberinin doğru yıla ait olanı.','Fotoğraflar — kullanım izniyle birlikte.'],6),
  ('adnan-menderes-anma-programi','Adnan Menderes ve Arkadaşlarını Anma Programı','Adnan Menderes, Fatin Rüştü Zorlu ve Hasan Polatkan''ın mezarları başında düzenlenen anma programı.','["Ekrem Eray Arda, Adnan Menderes, Fatin Rüştü Zorlu ve Hasan Polatkan''ın mezarları başında düzenlenen anma programına katıldı."]'::jsonb,null,null,'2026-09','Eylül 2026. Anma töreni Topkapı Anıt Mezar''da yapıldı; tören günü 17 Eylül 2026 görünüyor ancak teyit edilmedi.',array['etkinlikler'],'istanbul','katilim'::activity_kind,'published'::publication_status,array['Arda''nın katılımını doğrulayan kaynak bulunamadı — haberde adı geçmiyor.','Törenin kesin tarihi.','Arda''nın ilgili sosyal medya paylaşımının doğrudan bağlantısı.','Fotoğraflar — kullanım izniyle birlikte.'],7)
)
insert into activities (slug,title,summary,body,event_date,event_end_date,event_date_approx,date_note,categories,location,kind,status,missing_info,sort_order,published_at)
select slug,title,summary,body,event_date,event_end_date,event_date_approx,date_note,categories,location,kind,status,missing_info,sort_order,case when status = 'published' then now() else null end
from seed
on conflict (slug) do nothing;

insert into activity_sources (activity_id,label,url,publisher,confirms,retrieved_at,sort_order)
select a.id, s.label, s.url, s.publisher, s.confirms, '2026-09-25'::date, s.sort_order
from (values
  ('kartal-uluslararasi-tasarim-bulusmasi','Kartal Belediyesi, The Great Game — İstanbul 2026 yaz okuluna ev sahipliği yapıyor','https://ankahaber.net/haber/kartal-belediyesi-the-great-game-istanbul-2026-yaz-okuluna-ev-sahipligi-yapiyor-5847e0cb','ANKA Haber Ajansı','Programın 29 Ağustos – 8 Eylül 2026 tarihlerinde Kartal Belediyesi Makina Hangar''da, Politecnico di Torino DAD, AURA İstanbul, MSGSÜ ve UBT College Kosovo iş birliğiyle yapıldığını doğrular. Arda''nın adı geçmez.',0),
  ('kartal-uluslararasi-tasarim-bulusmasi','The Great Game Türkiye''de ilk kez Kartal''da uygulandı','https://www.karsmanset.com/haber/the-great-game-turkiyede-ilk-kez-kartalda-uygulandi-gelecegin-1779951.htm','Kars Manşet','Program tarihlerini, mekânı ve düzenleyicileri doğrular. Haberde adı geçen koordinatör Politecnico di Torino''dan Dr. Öğr. Üyesi Alp Arda''dır; Ekrem Eray Arda değildir.',1),
  ('kartal-belediye-meclisi-eylul-toplantisi','Kartal Belediyesi — Meclis Kararları sorgulama','https://e-belediye.kartal.bel.tr/BilgiSorgulama/MeclisKarar','Kartal Belediyesi','Resmî meclis kararlarının sorgulanabildiği kurumsal kayıt. Toplantı tarihi buradan teyit edilmeli; şu aşamada belirli bir oturum kaydı doğrulanmadı.',0),
  ('dragos-denizcilik-ve-kabotaj-bayrami','Kartal''da Kabotaj Bayramı coşkusu','https://www.kartal.bel.tr/Belediyemiz/Haberler/41646','Kartal Belediyesi','Etkinliğin Dragos Su Sporları Merkezi''nde 1 Temmuz''da düzenlendiğini doğrular. Yıl ve Arda''nın katılımı bu kayıttan teyit edilmedi.',0),
  ('adnan-menderes-anma-programi','Adnan Menderes ve arkadaşları kabirleri başında anıldı','https://www.sabah.com.tr/gundem/2026/09/18/adnan-menderes-ve-arkadaslari-kabirleri-basinda-anildi-sevgiyi-daragacina-cekemezsiniz','Sabah','Törenin Topkapı Anıt Mezar''da yapıldığını doğrular. Haberde anılan katılımcılar arasında Arda''nın adı geçmez.',0)
) as s(slug,label,url,publisher,confirms,sort_order)
join activities a on a.slug = s.slug
where not exists (select 1 from activity_sources existing where existing.activity_id = a.id and existing.url = s.url);
